terminal:
  colorScheme:
    name: Gruvbox Dark
    foreground: '#e6d4a3'
    background: '#1e1e1e'
    cursor: '#bbbbbb'
    colors:
      - '#161819'
      - '#f73028'
      - '#aab01e'
      - '#f7b125'
      - '#719586'
      - '#c77089'
      - '#7db669'
      - '#faefbb'
      - '#7f7061'
      - '#be0f17'
      - '#868715'
      - '#cc881a'
      - '#377375'
      - '#a04b73'
      - '#578e57'
      - '#e6d4a3'
  font: Cica Regular
  environment: {}
  profile: default-(powershell)
  bell: 'off'
  customShell: pwsh
  cursorBlink: false
hotkeys:
  profile: {}
  shell: {}
  toggle-fullscreen:
    - - Alt-Enter
serial: {}
ssh: {}
appearance:
  vibrancy: false
  opacity: 0.9
  vibrancyType: blur
  frame: thin
  dock: top
  dockFill: 1
  theme: Compact
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - ssh
  - serial
