
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew automake
brew bat
brew boost
brew cmake
brew coreutils
brew direnv
brew exa
brew exiftool
brew fd
brew ffmpeg
brew fish
brew fontconfig
brew freetype
brew fzf
brew gawk
brew gdbm
brew gettext
brew ghq
brew git
brew git-now
brew gmp
brew gnu-getopt
brew gnu-sed
brew go
brew grep
brew hadolint
brew icu4c
brew imagemagick
brew jemalloc
brew jpeg
brew lame
brew libevent
brew libogg
brew libpng
brew libtermkey
brew libtiff
brew libtool
brew libuv
brew libvorbis
brew libvpx
brew libvterm
brew libyaml
brew lua
brew lua@5.1
brew luajit
brew luarocks
brew mackup
brew mas
brew mosh
brew mpfr
brew msgpack
brew neovim --HEAD
brew node
brew openssl
brew opus
brew p7zip
brew pcre
brew pcre2
brew peco
brew perl
brew pkg-config
brew protobuf
brew python
brew python@2
brew readline
brew reattach-to-user-namespace
brew ripgrep
brew ruby
brew ruby-build
brew sdl2
brew snappy
brew source-highlight
brew sqlite
brew ssh-copy-id
brew ta-lib
brew theora
brew tig
brew tmux --HEAD
brew unibilium
brew vim --with-client-server --with-gettext --with-lua --with-override-system-vi --HEAD
brew watch
brew x264
brew x265
brew xvid
brew xz
brew youtube-dl
brew zlib

tap homebrew/cask-fonts
cask font-hack
cask font-ricty-diminished

tap homebrew/cask-versions

tap homebrew/cask
cask appcleaner
cask caffeine
cask dropbox
cask geektool
cask google-chrome
cask hammerspoon
cask iina
cask slack
cask virtualbox
cask vlc

tap heroku/brew
brew heroku
brew heroku-node

tap knqyf263/pet
brew pet

tap loadimpact/k6
brew k6

tap neovim/neovim

tap rcmdnk/file
brew brew-file

tap universal-ctags/universal-ctags
brew universal-ctags --HEAD

# Other Cask applications
cask appgrid
cask astro
cask docker
cask firefox
cask font-hack-nerd-font
cask google-backup-and-sync
cask google-japanese-ime
cask hyper
cask iterm2
cask vagrant
cask vivaldi
cask xquartz

# App Store applications
appstore 937984704 Amphetamine (4.0.4)
appstore 549083868 Display Menu (2.2.3)
