
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew automake
brew bat
brew boost
brew coreutils
brew direnv
brew exa
brew exiftool
brew fd
brew fish
brew fontconfig
brew freetype
brew fzf
brew gawk
brew gdbm
brew gettext
brew ghq
brew git
brew git-now
brew gmp
brew gnu-getopt
brew gnu-sed
brew go
brew grep
brew heroku
brew icu4c
brew imagemagick
brew jemalloc
brew jpeg
brew libevent
brew libpng
brew libtermkey
brew libtiff
brew libtool
brew libuv
brew libvterm
brew libyaml
brew lua
brew luajit
brew mackup
brew mas
brew mosh
brew mpfr
brew msgpack
brew neovim
brew node
brew openssl
brew p7zip
brew pcre
brew pcre2
brew peco
brew perl
brew pkg-config
brew protobuf
brew pyenv
brew python
brew python@2
brew rbenv
brew readline
brew reattach-to-user-namespace
brew ripgrep
brew ruby
brew ruby-build
brew source-highlight
brew sqlite
brew ssh-copy-id
brew tig
brew tmux --HEAD
brew unibilium
brew vim --with-client-server --with-gettext --with-lua --with-override-system-vi --with-tcl --HEAD
brew watch
brew xz
brew youtube-dl
brew zlib

tap homebrew/cask-fonts
cask font-hack
cask font-ricty-diminished

tap homebrew/cask-versions

tap homebrew/cask
cask appcleaner
cask astro
cask docker
cask geektool
cask google-chrome
cask hammerspoon
cask iina
cask slack
cask virtualbox

tap heroku/brew
brew heroku-node

tap knqyf263/pet
brew pet

tap loadimpact/k6
brew k6

tap neovim/neovim

tap rcmdnk/file
brew brew-file

tap universal-ctags/universal-ctags
brew universal-ctags --HEAD

# Other Cask applications
cask appgrid
cask caffeine
cask dropbox
cask font-hack-nerd-font
cask google-backup-and-sync
cask google-japanese-ime
cask hyper
cask iterm2
cask vagrant
cask xquartz

# App Store applications
appstore 937984704 Amphetamine (4.0.2)
appstore 549083868 Display Menu (2.2.3)
