
# tap repositories and their packages

tap homebrew/core
brew adwaita-icon-theme
brew atk
brew autoconf
brew automake
brew bat
brew bdw-gc
brew boost
brew cairo
brew cmake
brew coreutils
brew direnv
brew easy-tag
brew exa
brew exiftool
brew fd
brew ffmpeg
brew fish
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fx
brew fzf
brew gawk
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghq
brew giflib
brew git
brew git-now
brew glib
brew gmp
brew gnu-getopt
brew gnu-sed
brew go
brew gobject-introspection
brew graphite2
brew grep
brew gsettings-desktop-schemas
brew gtk+3
brew hadolint
brew harfbuzz
brew hicolor-icon-theme
brew hub
brew icu4c
brew id3lib
brew imagemagick
brew jemalloc
brew jpeg
brew jq
brew jvgrep
brew lame
brew leptonica
brew libass
brew libcroco
brew libepoxy
brew libevent
brew libffi
brew libid3tag
brew libogg
brew libomp
brew libpng
brew librsvg
brew libssh2
brew libtermkey
brew libtiff
brew libtool
brew libuv
brew libvorbis
brew libvpx
brew libvterm
brew libyaml
brew little-cms2
brew lua
brew lua@5.1
brew luajit
brew luarocks
brew lzo
brew mackup
brew make
brew mas
brew mosh
brew mpfr
brew msgpack
brew ncurses
brew neovim
brew node
brew nspr
brew nss
brew oniguruma
brew opencore-amr
brew openjpeg
brew openssl
brew opus
brew p7zip
brew pandoc
brew pango
brew pcre
brew pcre2
brew peco
brew perl
brew pixman
brew pkg-config
brew poppler
brew protobuf
brew python
brew python@2
brew qt
brew ranger
brew readline
brew reattach-to-user-namespace
brew ripgrep
brew rtmpdump
brew ruby
brew ruby-build
brew rust
brew sdl2
brew snappy
brew source-highlight
brew speex
brew sqlite
brew ssh-copy-id
brew ta-lib
brew taglib
brew terminal-notifier
brew tesseract
brew theora
brew tig
brew tmux --HEAD
brew tree
brew unibilium
brew vagrant-completion
brew vim --with-client-server --with-gettext --with-lua --with-override-system-vi --HEAD
brew w3m
brew watch
brew watchexec
brew wavpack
brew webp
brew x264
brew x265
brew xvid
brew xz
brew youtube-dl
brew zlib
brew zola
brew zsh --HEAD

tap homebrew/cask-fonts
cask font-hack
cask font-ricty-diminished

tap homebrew/cask-versions

tap homebrew/cask
cask alacritty
cask amazon-music
cask appgrid
cask caffeine
cask dropbox
cask geektool
cask google-chrome
cask hammerspoon
cask iina
cask lyrics-master
cask powershell
cask vagrant
cask visual-studio-code
cask vlc
cask xquartz

tap goodwithtech/dockle
brew dockle

tap heroku/brew
brew heroku
brew heroku-node

tap knqyf263/pet
brew pet

tap loadimpact/k6
brew k6

tap mananapr/cfiles
brew cfiles

tap neovim/neovim

tap rcmdnk/file
brew brew-file

tap universal-ctags/universal-ctags
brew universal-ctags --HEAD

# Other Cask applications
cask alfred
cask appcleaner
cask astro
cask docker
cask firefox
cask font-hack-nerd-font
cask google-backup-and-sync
cask google-japanese-ime
cask hyper
cask iterm2
cask mp3tag
cask slack
cask virtualbox
cask vivaldi
cask wkhtmltopdf

# App Store applications
appstore 937984704 Amphetamine (4.1.6)
appstore 549083868 Display Menu (2.2.3)
