[config]
skip_core_tasks = false

[tasks.init]
script = '''
echo init !!!!!!
'''

[tasks.default]
script = '''
echo Hello world ! %*
'''
dependencies = ['powershell', 'duckscript-example']

[tasks.powershell]
script_runner = "powershell"
script_extension = "ps1"
script = '''
Write-Host "Hello world !"
'''

[tasks.duckscript-example]
script_runner = "@duckscript"
script = '''
task_name = get_env CARGO_MAKE_CURRENT_TASK_NAME
echo The currently running cargo make task is: ${task_name}

# since all env vars are auto loaded as duckscript variables by cargo-make
# you can access them directly
echo The currently running cargo make task is: ${CARGO_MAKE_CURRENT_TASK_NAME}

cd .. # this changes cargo-make current working directory (cargo-make will revert to original directory after script execution)
pwd
set_env CARGO_MAKE_CURRENT_TASK_NAME tricking_cargo_make
echo The currently running cargo make task is: ${CARGO_MAKE_CURRENT_TASK_NAME}
'''
