# ======================================================================
# Unite {{{1
# ======================================================================
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-help'
on_source = 'unite.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'unite.vim'
on_cmd = 'JunkfileOpen'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-ref'
on_source = 'unite.vim'
on_cmd = 'Ref'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-filetype'
on_source = 'unite.vim'

[[plugins]]
repo = 'sorah/unite-ghq'
on_source = 'unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = 'unite.vim'

[[plugins]]
repo = 'mattn/unite-vim_advent-calendar'
on_source = 'unite.vim'

[[plugins]]
repo = 'mattn/unite-advent_calendar'
on_source = 'unite.vim'

[[plugins]]
repo = 'rhysd/unite-codic.vim'
depends = 'codic-vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'lambdalisue/unite-grep-vcs'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/neossh.vim'
on_source = 'unite.vim'

# ======================================================================
# Complement {{{1
# ======================================================================
[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neco-syntax'
depends = 'neocomplete.vim'
on_i = 1

# [[plugins]]
# repo = 'ujihisa/neco-look'
# depends = 'neocomplete.vim'
# on_i = 1

[[plugins]]
repo = 'Shougo/neco-vim'
depends = 'neocomplete.vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_i = 1
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# ======================================================================
# Search {{{1
# ======================================================================
[[plugins]]
repo = 'thinca/vim-visualstar'
on_map = '<Plug>'

[[plugins]]
repo = 't9md/vim-quickhl'
on_map = '<Plug>'

# [[plugins]]
# repo = 'osyo-manga/vim-over'
# on_map = '<Plug>'

# ======================================================================
# QuickRun {{{1
# ======================================================================
[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>'
on_cmd = 'QuickRun'
on_source = 'vim-watchdogs'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
depends = 'vim-quickrun'
on_source = ['vim-quickrun', 'vim-watchdogs']

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
on_ft = 'all'
depends = 'vim-quickrun'

# ======================================================================
# Comment {{{1
# ======================================================================
[[plugins]]
repo = 'tyru/caw.vim'
on_map = '<Plug>'

# ======================================================================
# Visual {{{1
# ======================================================================
[[plugins]]
repo = 'Yggdroot/indentLine'
# on_ft = ['javascript', 'ruby', 'go', 'haskell', 'markdown', 'vim', 'ps1']
on_ft = 'all'

# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# on_ft = ['javascript', 'ruby', 'go', 'haskell', 'markdown', 'vim']

# [[plugins]]
# repo = 'kien/rainbow_parentheses.vim'
# on_cmd = 'RainbowParenthesesToggle'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
on_ft = 'all'


# ======================================================================
# Session {{{1
# ======================================================================
[[plugins]]
repo = 'osyo-manga/vim-reanimate'
on_source = 'unite.vim'
on_cmd = 'ReanimateLoad'

# ======================================================================
# Operators {{{1
# ======================================================================
[[plugins]]
repo = 'kana/vim-operator-user'
on_ft = 'all'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = '<Plug>'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = '<Plug>'

[[plugins]]
repo = 'chikatoike/concealedyank.vim'
depends = 'vim-operator-user'
on_ft = 'vimshell'
on_map = '<Plug>'

[[plugins]]
repo = 'osyo-manga/vim-operator-blockwise'
depends = 'vim-operator-user'
on_map = '<Plug>'

[[plugins]]
repo = 'rhysd/vim-operator-trailingspace-killer'
depends = 'vim-operator-user'
on_map = '<Plug>'

[[plugins]]
repo = 'rhysd/vim-clang-format'
depends = 'vim-operator-user'
on_map = '<Plug>'

[[plugins]]
repo = 'osyo-manga/vim-operator-search'
depends = 'vim-operator-user'
on_map = '<Plug>'

[[plugins]]
repo = 'tyru/operator-star.vim'
depends = ['vim-operator-user', 'vim-visualstar']
on_map = '<Plug>'

[[plugins]]
repo = 'haya14busa/vim-operator-flashy'
depends = ['vim-operator-user']
on_map = '<Plug>'

# ======================================================================
# Textobjs {{{1
# ======================================================================
[[plugins]]
repo = 'kana/vim-textobj-user'
on_ft = 'all'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
depends = 'vim-textobj-user'
on_map = '<Plug>'

[[plugins]]
repo = 'kana/vim-textobj-entire'
depends = 'vim-textobj-user'
on_map = '<Plug>'

[[plugins]]
repo = 'kana/vim-textobj-fold'
depends = 'vim-textobj-user'
on_map = '<Plug>'

[[plugins]]
repo = 'kana/vim-textobj-function'
depends = 'vim-textobj-user'
on_map = '<Plug>'

[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = 'vim-textobj-user'
on_map = '<Plug>'

[[plugins]]
repo = 'gilligan/textobj-lastpaste'
depends = 'vim-textobj-user'
on_map = '<Plug>'

# ======================================================================
# Git {{{1
# ======================================================================
[[plugins]]
repo = 'tpope/vim-fugitive'
on_ft = 'all'

[[plugins]]
repo = 'gregsexton/gitv'
on_cmd = 'Gitv'

[[plugins]]
repo = 'rhysd/github-complete.vim'
on_ft = 'gitcommit'

# [[plugins]]
# repo = 'airblade/vim-gitgutter'
# on_ft = 'all'

# ======================================================================
# Filetype (haskell) {{{1
# ======================================================================
[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = 'haskell'

[[plugins]]
repo = 'nbouscal/vim-stylish-haskell'
on_ft = 'haskell'

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = 'haskell'

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = 'haskell'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

# ======================================================================
# Filetype (css) {{{1
# ======================================================================
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

# ======================================================================
# Filetype (ruby) {{{1
# ======================================================================
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = 'ruby'

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = 'ruby'

# ======================================================================
# Filetype (vim) {{{1
# ======================================================================
[[plugins]]
repo = 'thinca/vim-themis'
on_ft = 'vim'

# ======================================================================
# Filetype (vimperator) {{{1
# ======================================================================
[[plugins]]
repo = 'superbrothers/vim-vimperator'
on_ft = 'vimperator'

# ======================================================================
# Filetype (markdown) {{{1
# ======================================================================
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'mattn/vim-maketable'
on_cmd = 'MakeTable'

# ======================================================================
# Filetype (html) {{{1
# ======================================================================
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'markdown', 'xml']

# ======================================================================
# Filetype (javascript) {{{1
# ======================================================================
# [[plugins]]
# repo = 'jiangmiao/simple-javascript-indenter'
# on_ft = 'javascript'

# [[plugins]]
# repo = 'jelera/vim-javascript-syntax'
# on_ft = 'javascript'

# [[plugins]]
# repo = 'jason0x43/vim-js-indent'
# on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'jsx']

# [[plugins]]
# repo = 'mephux/vim-jsfmt'
# on_ft = ['javascript', 'jsx']

[[plugins]]
repo = 'maksimr/vim-jsbeautify'
on_func = ['JsBeautify', 'HtmlBeautify', 'CSSBeautify']

# ======================================================================
# Filetype (coffee-script) {{{1
# ======================================================================
[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

# [[plugins]]
# repo = 'marijnh/tern_for_vim'
# on_ft = ['javascript', 'coffee']
# on_func = 'tern'

# ======================================================================
# Filetype (typescript) {{{1
# ======================================================================
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = 'typescript'

# ======================================================================
# Filetype (python) {{{1
# ======================================================================
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

# ======================================================================
# Filetype (cpp) {{{1
# ======================================================================
[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = 'cpp'

[[plugins]]
repo =  'osyo-manga/vim-marching'
on_ft = 'cpp'

[[plugins]]
repo = 'rhysd/wandbox-vim'
on_ft = 'cpp'

# ======================================================================
# Filetype (go) {{{1
# ======================================================================
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

# ======================================================================
# Filetype (ps1) {{{1
# ======================================================================
[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = 'ps1'

# [[plugins]]
# repo = 'vim-scripts/Windows-PowerShell-indent-enhanced.git'
# on_ft = 'ps1'


# ======================================================================
# Filetype (rst) {{{1
# ======================================================================
[[plugins]]
repo = 'Rykka/riv.vim'
on_ft = 'rst'

# ======================================================================
# Filetype (clojure) {{{1
# ======================================================================
[[plugins]]
repo =  'tpope/vim-fireplace'
depends = ['vim-classpath', 'vim-clojure-static']
on_ft = 'clojure'

# [[plugins]]
# repo = 'thinca/vim-ft-clojure'
# on_ft = 'clojure'

[[plugins]]
repo = 'guns/vim-clojure-static'
on_ft = 'clojure'

# ======================================================================
# Filetype (toml) {{{1
# ======================================================================
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# ======================================================================
# Filetype (plantuml) {{{1
# ======================================================================
[[plugins]]
repo =  'aklt/plantuml-syntax'
on_ft = 'plantuml'

# ======================================================================
# Filetype (diff) {{{1
# ======================================================================
[[plugins]]
repo = 'thinca/vim-ft-diff_fold'
on_ft = 'diff'

# ======================================================================
# Filetype (json) {{{1
# ======================================================================
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

# ======================================================================
# Filetype (help) {{{1
# ======================================================================
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'
on_ft = 'help'

# ======================================================================
# Application {{{1
# ======================================================================
[[plugins]]
repo = 'basyura/J6uil.vim'
on_func = 'J6uil'
on_source = 'unite.vim'
depends = 'webapi-vim'
on_cmd = 'J6Uil'

[[plugins]]
repo =  'basyura/TweetVim''
depends = ['twibill.vim', 'open-browser.vim', 'bitly.vim', 'favstar-vim', 'webapi-vim']
on_source = 'unite.vim'
on_cmd = ['TweetVim', 'TweetVimUserStream','TweetVimSay']
on_ft = 'tweetvim'

[[plugins]]
repo = 'supermomonga/jazzradio.vim'
on_source = 'unite.vim'
on_cmd = 'JazzradioPlay'

[[plugins]]
repo = 'mattn/webapi-vim'

# ======================================================================
# Others {{{1
# ======================================================================
[[plugins]]
repo = 'rhysd/clever-f.vim'
on_map = '<Plug>'

# [[plugins]]
# repo = 'rhysd/accelerated-jk'
# on_map = '<Plug>'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = '<Plug>'
explorer = 1
on_cmd = 'VimFiler'

[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = '<Plug>'
on_cmd = 'VimShell'

# [[plugins]]
# repo = 'supermomonga/vimshell-pure.vim'
# depends = 'vimshell.vim'
# on_source = 'vimshell.vim'

[[plugins]]
repo = 'yomi322/vim-gitcomplete'
on_ft = 'vimshell'

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'

[[plugins]]
repo = 'vim-jp/vital.vim'
on_cmd = 'Vitalize'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_cmd = 'CtrlP'

# [[plugins]]
# repo = 'thinca/vim-fontzoom'
# gui = 1
# on_map = '<Plug>'

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_ft = ['unite', 'quickfix']
on_cmd = 'Qfreplace'

# [[plugins]]
# repo = 'itchyny/vim-external'
# on_map = '<Plug>'

[[plugins]]
repo = 'tyru/restart.vim'
gui = 1
on_cmd = 'Restart'

# [[plugins]]
# repo = 'tyru/winmove.vim'
# depends = 'vim-submode'
# on_map = '<Plug>'
# gui = 1
# augroup = 'winmove'

[[plugins]]
repo = 'matchit.zip'
on_map = [['nxo', '%', 'g%']]

[[plugins]]
repo = 't9md/vim-choosewin'
on_map = '<Plug>'
on_cmd = ['FontReview', 'FontPerfSmall', 'ChooseWin', 'FontPerfLarge']

# [[plugins]]
# repo = 'lambdalisue/vim-fullscreen'
# gui = 1
# on_map = '<Plug>'

[[plugins]]
repo = 'syngan/vim-vimlint'
depends = 'vim-vimlparser'
on_func = 'vimlint'

[[plugins]]
repo = 'osyo-manga/vim-jplus'
on_map = '<Plug>'

[[plugins]]
repo = 'lambdalisue/vim-gista'
on_cmd = 'Gista'
on_map = '<Plug>'
on_source = 'unite.vim'

# [[plugins]]
# repo = 'kana/vim-niceblock'
# on_map = '<Plug>'

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = '<Plug>(EasyAlign)'

[[plugins]]
repo = 'tyru/capture.vim'
on_cmd = 'Capture'

[[plugins]]
repo = 'thinca/vim-prettyprint'
on_cmd = 'PP'

[[plugins]]
repo = 'itchyny/thumbnail.vim'
on_cmd = 'Thumbnail'

[[plugins]]
repo = 'mattn/vimplenote-vim'
on_cmd = 'VimpleNote'

[[plugins]]
repo = 'koron/codic-vim'
on_cmd = 'Codic'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
on_cmd = 'Ctags'

# [[plugins]]
# repo = 'yassu/todo-env.vim'
# on_ft = 'todo'

[[plugins]]
repo = 'fuenor/qfixhowm'
depends = 'qfixgrep'
on_func = 'qfixmemo'

[[plugins]]
repo = 'mattn/benchvimrc-vim'
on_cmd = 'BenchVimrc'

# [[plugins]]
# repo = 'seletskiy/vim-autosurround'
# on_func = 'AutoSurround'

[[plugins]]
repo = 'Chiel92/vim-autoformat'
on_cmd = 'Autoformat'

[[plugins]]
repo = 'glidenote/memolist.vim'
on_cmd = ['MemoNew', 'MemoList', 'MemoGrep']

[[plugins]]
repo ='ujihisa/vimshell-ssh'
on_source = 'vimshell.vim'

