providers: 
  webSearchOrder: 
    []
symbolPreset: nerd
theme: 
  dark: dark-tokyo-night
setupVersion: 1
autolearn: 
  enabled: true
modelRoles: 
  smol: openrouter/~deepseek/deepseek-v4-flash-latest
  slow: anthropic/claude-opus-5
  plan: kimi-code/k3
  default: openrouter/~deepseek/deepseek-v4-flash-latest
  designer: anthropic/claude-opus-5
  tiny: openrouter/~deepseek/deepseek-v4-flash-latest
  advisor: kimi-code/k3
defaultThinkingLevel: auto
memory: 
  backend: local
hideThinkingBlock: true