# =============================================================================
# File        : default.yml
# Author      : yukimemi
# Last Change : 2024/06/22 16:47:38.
# =============================================================================

backend: Auto
toggle_key: OFF
show_notifications: true
search_shortcut: ALT+SHIFT+SPACE
