# =============================================================================
# File        : default.yml
# Author      : yukimemi
# Last Change : 2024/08/05 10:07:25.
# =============================================================================

backend: Auto
toggle_key: OFF
show_notifications: true
search_shortcut: ALT+SHIFT+SPACE
