# =============================================================================
# File        : rdp.yml
# Author      : yukimemi
# Last Change : 2024/06/16 23:50:31.
# =============================================================================

filter_exec: mstsc
backend: Clipboard

