// =============================================================================
// File        : pluginstatus.ts
// Author      : yukimemi
// Last Change : 2024/09/29 18:54:46.
// =============================================================================

export const pluginStatus = {
  autopairs: false,
  barbar: true,
  barbecue: false,
  bufferline: false,
  buffertabs: false,
  scrollbar: false,
  satellite: true,
  cmp: true,
  coc: false,
  oil: false,
  ddc: false,
  vsnip: false,
  denippet: true,
  ddu: true,
  ddufiler: false,
  clap: false,
  fern: false,
  fall: false,
  heirline: false,
  hlchunk: true,
  indentblankline: false,
  insx: true,
  lualine: true,
  modesearch: false,
  neotree: true,
  notifier: false,
  nvimnotify: false,
  fidget: true,
  nvimtree: false,
  snipewin: true,
  ultimatepair: false,
  vimwiki: false,
  vscode: false,
  windowpicker: false,
  yankround: true,
  yanky: false,
  virtcolumn: true,
  neocolumn: false,
  quickrun: true,
  overseer: true,
};
