// =============================================================================
// File        : pluginstatus.ts
// Author      : yukimemi
// Last Change : 2024/11/04 19:20:13.
// =============================================================================

export const pluginStatus = {
  autopairs: false,
  barbar: false,
  barbecue: false,
  blink: true,
  bufferline: false,
  buffertabs: false,
  care: false,
  clap: false,
  cmp: false,
  coc: false,
  ddc: false,
  ddu: true,
  ddufiler: false,
  denippet: false,
  fall: false,
  fern: false,
  fidget: true,
  heirline: false,
  hlchunk: true,
  indentblankline: false,
  insx: true,
  lualine: true,
  modesearch: false,
  neocolumn: false,
  neotree: true,
  notifier: false,
  nvimnotify: false,
  nvimtree: false,
  oil: false,
  overseer: true,
  quickrun: true,
  satellite: false,
  scrollbar: false,
  snipewin: true,
  ultimatepair: false,
  vimwiki: false,
  virt_column: false,
  virtcolumn: true,
  vscode: false,
  vsnip: false,
  windowpicker: false,
  windows: false,
  yankround: true,
  yanky: false,
};
