// =============================================================================
// File        : pluginstatus.ts
// Author      : yukimemi
// Last Change : 2024/11/24 00:09:55.
// =============================================================================

export const pluginStatus = {
  autopairs: false,
  barbar: false,
  barbecue: false,
  blink: false,
  bufferline: false,
  buffertabs: false,
  care: false,
  fuzzymotion: true,
  initial: false,
  clap: false,
  cmp: false,
  coc: false,
  ddc: true,
  ddu: false,
  ddufiler: false,
  denippet: true,
  fall: true,
  fern: false,
  fidget: true,
  heirline: false,
  hlchunk: true,
  indentblankline: false,
  insx: true,
  lualine: true,
  modesearch: false,
  neocolumn: false,
  neotest: false,
  neotree: false,
  notifier: false,
  nvimnotify: false,
  nvimtree: false,
  oil: false,
  overseer: true,
  quickrun: true,
  satellite: false,
  scrollbar: false,
  snipewin: true,
  telescope: false,
  ultimatepair: false,
  vimtest: true,
  vimwiki: false,
  virt_column: false,
  virtcolumn: true,
  vscode: false,
  vsnip: false,
  windowpicker: false,
  windows: false,
  yankround: true,
  yanky: false,
  yazi: true,
};
