sort_order = "recent_first"
search_mode = "migemo"
hide_on_blur = true
window_width = 700
max_items = 10
max_completions = 8
opacity = 0.9
icon_style = "svg"

[log]
level = "debug"

[keybindings]
launch = "Ctrl+Enter"
next = "Ctrl+n"
prev = "Ctrl+p"
confirm = "Enter"
arg_mode = "Tab"
accept_word = "Ctrl+f"
accept_line = "Ctrl+e"
delete_word = "Ctrl+w"
delete_line = "Ctrl+u"
close = "Escape"

[theme]
preset = "tokyo-night"

[[apps]]
name = "Neovide"
path = "neovide"
completion = "path"

[[apps]]
name = "Todo"
path = "hitori.cmd"
args = ["{{ env.USERPROFILE }}/.memolist/todo.md"]

[[apps]]
name = "Open Project"
path = "neovide"
args = ["{{ env.USERPROFILE }}/src/{{ args }}"]
completion = "path"

[[apps]]
name = "MemoNew"
path = "nvim"
args = ['~/.memolist/{{ now() | date(format="%Y%m%d") }}-{{ args }}.md']
completion = "none"

[[apps]]
name = "MemoList"
path = "nvim"
args = ["~/.memolist/{{ args }}"]
completion = "path"
completion_search_mode = "migemo"

[[apps]]
name = "Scoop"
path = "scoop"
completion = "list"
completion_list = [
  "install",
  "uninstall",
  "update",
  "search",
  "list",
  "info",
  "status",
  "cleanup",
  "bucket",
  "cache",
  "checkup",
  "config",
  "hold",
  "unhold",
  "reset",
  "shim",
  "which",
]

[[apps]]
name = "Git"
path = "git"
completion = "command"
completion_command = "git branch --format='%(refname:short)'"
workdir = "~/src/github.com/yukimemi/shun"

[[apps]]
name = "Google"
path = "https://www.google.com/search?q={{ args | urlencode }}"

[[apps]]
name = "GitHub Search"
path = "https://github.com/search?q={{ args | urlencode }}"

[[apps]]
name = "Perplexity"
path = "https://www.perplexity.ai/search?q={{ args | urlencode }}"

[[apps]]
name = "Phind"
path = "https://www.phind.com/search?q={{ args | urlencode }}"

[[scan_dirs]]
path = "~/src/github.com/yukimemi/ps1/cmd"
recursive = false
extensions = ["cmd"]

[[scan_dirs]]
path = "~/.local/share/chezmoi/win/scripts"
recursive = false
extensions = ["ps1"]

[[scan_dirs]]
path = "C:/Windows/System32"
recursive = false
extensions = ["exe"]
