#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    active_window_border_color   0xffdc143c     \
    active_window_opacity        1.0            \
    auto_balance                 on             \
    bottom_padding               12             \
    focus_follows_mouse          autoraise      \
    insert_feedback_color        0xffd75f5f     \
    layout                       bsp            \
    left_padding                 12             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    mouse_follows_focus          off            \
    mouse_modifier               fn             \
    normal_window_border_color   0xff555555     \
    normal_window_opacity        0.8            \
    right_padding                12             \
    split_ratio                  0.50           \
    split_type                   auto           \
    top_padding                  12             \
    window_animation_duration    0.0            \
    window_border                on             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border_radius         12             \
    window_border_width          2              \
    window_gap                   6              \
    window_opacity               on             \
    window_origin_display        default        \
    window_placement             second_child   \
    window_shadow                on             \
    window_topmost               off

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^mpv$" manage=off
yabai -m rule --add app="^vlc$" manage=off
# yabai -m rule --add app="^WezTerm$" manage=off

echo "yabai configuration loaded.."

