# vim: ft=toml ts=2 sw=2 et :

# The path of root directory to manage cloned repositories.
root = "~/src"

# Patterns to search local repositories.
includes = [
  "~/src",
  "~/.go/src",
  "~/.dotfiles",
  "~/.private",
  "~/.cache/vim/pack",
  "~/.cache/nvim/pack",
  "~/.cache/nvim/dein/repos",
  "~/Documents/src"
]

# Patterns to ignore repositories.
excludes = []
