complete -c dot -n "__fish_use_subcommand" -s v -l verbose -d 'Use verbose output'
complete -c dot -n "__fish_use_subcommand" -s n -l dry-run -d 'do not actually perform I/O operations'
complete -c dot -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c dot -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c dot -n "__fish_use_subcommand" -f -a "check" -d 'Check the files are correctly linked to the right places'
complete -c dot -n "__fish_use_subcommand" -f -a "link" -d 'Create all of the symbolic links into home directory'
complete -c dot -n "__fish_use_subcommand" -f -a "clean" -d 'Remote all of registered links from home directory'
complete -c dot -n "__fish_use_subcommand" -f -a "root" -d 'Show the location of dotfiles repository and exit'
complete -c dot -n "__fish_use_subcommand" -f -a "clone" -d 'Clone dotfiles repository from remote'
complete -c dot -n "__fish_use_subcommand" -f -a "init" -d 'Clone dotfiles repository from remote & make links'
complete -c dot -n "__fish_use_subcommand" -f -a "completion" -d 'Generate completion scripts'
complete -c dot -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c dot -n "__fish_seen_subcommand_from check" -s h -l help -d 'Prints help information'
complete -c dot -n "__fish_seen_subcommand_from check" -s V -l version -d 'Prints version information'
complete -c dot -n "__fish_seen_subcommand_from link" -s h -l help -d 'Prints help information'
complete -c dot -n "__fish_seen_subcommand_from link" -s V -l version -d 'Prints version information'
complete -c dot -n "__fish_seen_subcommand_from clean" -s h -l help -d 'Prints help information'
complete -c dot -n "__fish_seen_subcommand_from clean" -s V -l version -d 'Prints version information'
complete -c dot -n "__fish_seen_subcommand_from root" -s h -l help -d 'Prints help information'
complete -c dot -n "__fish_seen_subcommand_from root" -s V -l version -d 'Prints version information'
complete -c dot -n "__fish_seen_subcommand_from clone" -s h -l help -d 'Prints help information'
complete -c dot -n "__fish_seen_subcommand_from clone" -s V -l version -d 'Prints version information'
complete -c dot -n "__fish_seen_subcommand_from init" -s h -l help -d 'Prints help information'
complete -c dot -n "__fish_seen_subcommand_from init" -s V -l version -d 'Prints version information'
complete -c dot -n "__fish_seen_subcommand_from completion" -s h -l help -d 'Prints help information'
complete -c dot -n "__fish_seen_subcommand_from completion" -s V -l version -d 'Prints version information'
complete -c dot -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c dot -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
