# =============================================================================
# File        : config.toml
# Author      : yukimemi
# Last Change : 2026/09/22 01:37:06.
# =============================================================================

[global]
root = "~/src"

[global.ui]
own_owners = ["yukimemi"]

[[pinned]]
path = "~/dotfiles"
