# =============================================================================
# File        : config.toml
# Author      : yukimemi
# Last Change : 2026/05/31 19:55:54.
# =============================================================================

[global]
root = "~/src"

[global.ui]
own_owners = ["yukimemi"]
