app:
  tab: -:-:-
  separator: gray:-:-
statusbar:
  text: black:-:-
  bg: "#ffffff"
autocomplete:
  normalbg: "#3e4359"
  selectbg: "#5c6586"
tweet:
  annotation: blue:-:-
  detail: gray:-:-
  like: pink:-:-
  rt: green:-:-
  hashtag: blue:-:-
  mention: blue:-:-
  pollgraph: blue:-:-
  polldetail: gray:-:-
user:
  name: white:-:b
  username: gray:-:i
  verified: blue:-:-
  private: gray:-:-
  detail: gray:-:-
  tweetsmetricstext: black:-:-
  tweetsmetricsbg: "#a094c7"
  followingmetricstext: black:-:-
  followingmetricsbg: "#84a0c6"
  followersmetricstext: black:-:-
  followersmetricsbg: "#89b8c2"
