[header]
prefix = ["header"]
body = """
@echo off
rem ============================================================================
rem File        : ${TM_FILENAME}
rem Author      : yukimemi
rem Last Change : 2025/05/11 09:06:46.
rem ============================================================================

rem setlocal enabledelayedexpansion
set tm=%time: =0%
set today=%date:~-10,4%%date:~-5,2%%date:~-2,2%
set nowtime=%tm:~0,2%%tm:~3,2%%tm:~6,2%%tm:~9,2%
set now=%today%_%nowtime%
set cmdDrive=%~d0
set cmdDir=%~dp0
set cmdFile=%~f0
set cmdName=%~n0
set cmdFileName=%~nx0

pushd "%cmdDir%"

set BATLOGPATH="%cmdDir%%cmdName%_%computername%_%now%.log"

rem call :main %* >> %BATLOGPATH% 2>&1
call :main %*

set exitCode=%errorlevel%

echo Exit Code: [%exitCode%]

pause
popd

exit /b %exitCode%

rem ============================================================================
:main

exit /b %errorlevel%

rem ============================================================================
:log
set msg=%*
set tm=%time: =0%
echo %date% %tm% %msg%
exit /b
"""
