[header]
prefix = ["header"]
body = """
# =============================================================================
# File        : ${TM_FILENAME}
# Author      : yukimemi
# Last Change : 2024/04/27 18:21:59.
# =============================================================================
"""

