[header]
prefix = ["header"]
body = """
# =============================================================================
# File        : ${TM_FILENAME}
# Author      : yukimemi
# Last Change : 2024/05/01 16:02:09.
# =============================================================================
"""
