[new]
prefix = ["header"]
body = """
# =============================================================================
# File        : ${TM_FILENAME}
# Author      : yukimemi
# Last Change : 2023/12/24 00:12:31.
# =============================================================================
"""

