# =============================================================================
# File       : dein.toml
# Author     : yukimemi
# Last Change: 2021/02/06 17:50:40.
# =============================================================================

# ==================== Dein ======================

[[plugins]]
repo = "Shougo/dein.vim"

# ==================== Visual ====================

[[plugins]]
on_event = ["CursorHold", "FocusLost"]
repo = "andymass/vim-matchup"

[[plugins]]
hook_add = '''
source $VIM_PATH/rc/vim-cursorword.vim
'''
on_event = ["CursorHold", "FocusLost"]
repo = 'itchyny/vim-cursorword'

[[plugins]]
hook_add = '''
source $VIM_PATH/rc/vim-parenmatch.vim
'''
on_event = ["CursorHold", "FocusLost"]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
hook_add = '''
source $VIM_PATH/rc/vim-quickhl.vim
'''
on_event = ["CursorHold", "FocusLost"]
repo = 't9md/vim-quickhl'

# ==================== Utility ===================

[[plugins]]
hook_add = '''
source $VIM_PATH/rc/vim-edgemotion.vim
'''
on_map = '<Plug>'
repo = 'haya14busa/vim-edgemotion'

[[plugins]]
hook_add = '''
source $VIM_PATH/rc/vim-ambicmd.vim
'''
repo = 'thinca/vim-ambicmd'

[[plugins]]
repo = 'tpope/vim-repeat'

# ==================== Textobjs ==================

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'gilligan/textobj-lastpaste'

depends = 'vim-textobj-user'
hook_add = '''
source $VIM_PATH/rc/textobj-lastpaste.vim
'''
on_map = {n = '<Plug>', x = '<Plug>', o = '<Plug>'}

[[plugins]]
repo = 'kana/vim-textobj-entire'

depends = 'vim-textobj-user'
hook_add = '''
source $VIM_PATH/rc/vim-textobj-entire.vim
'''
on_map = {n = '<Plug>', x = '<Plug>', o = '<Plug>'}

[[plugins]]
repo = 'kana/vim-textobj-fold'

depends = 'vim-textobj-user'
hook_add = '''
source $VIM_PATH/rc/vim-textobj-fold.vim
'''
on_map = {n = '<Plug>', x = '<Plug>', o = '<Plug>'}

[[plugins]]
repo = 'kana/vim-textobj-function'

depends = 'vim-textobj-user'
hook_add = '''
source $VIM_PATH/rc/vim-textobj-function.vim
'''
on_map = {n = '<Plug>', x = '<Plug>', o = '<Plug>'}

[[plugins]]
repo = 'kana/vim-textobj-indent'

depends = 'vim-textobj-user'
hook_add = '''
source $VIM_PATH/rc/vim-textobj-indent.vim
'''
on_map = {n = '<Plug>', x = '<Plug>', o = '<Plug>'}

[[plugins]]
repo = 'kana/vim-textobj-line'

depends = 'vim-textobj-user'
hook_add = '''
source $VIM_PATH/rc/vim-textobj-line.vim
'''
on_map = {n = '<Plug>', x = '<Plug>', o = '<Plug>'}

# ==================== Operators =================

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
depends = 'vim-operator-user'
hook_add = '''
source $VIM_PATH/rc/vim-operator-replace.vim
'''
on_map = '<Plug>'
repo = 'kana/vim-operator-replace'

[[plugins]]
depends = 'vim-operator-user'
hook_add = '''
source $VIM_PATH/rc/vim-operator-search.vim
'''
on_map = '<Plug>'
repo = 'osyo-manga/vim-operator-search'

[[plugins]]
on_event = ['CursorHold', 'CursorMoved', 'FocusLost']
repo = 'machakann/vim-sandwich'

# ==================== Search ====================

[[plugins]]
hook_add = '''
source $VIM_PATH/rc/vim-asterisk.vim
'''
on_map = '<Plug>'
repo = 'haya14busa/vim-asterisk'

[[plugins]]
on_event = ["CmdlineEnter", "CmdwinEnter"]
repo = 'markonm/traces.vim'

[[plugins]]
on_event = ['CursorHold', 'CursorMoved', 'FocusLost']
repo = 'unblevable/quick-scope'

# vim:fdm=marker fdc=3 ft=toml:
