#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    autocomplete_method = 'coc'
    automatic_update = false
    bootstrap_after = "init#after"
    bootstrap_before = "init#before"
    buffer_index_type = 4
    colorscheme = "material"
    colorscheme_bg = "dark"
    enable_guicolors = true
    enable_statusline_mode = false
    enable_tabline_filetype_icon = true
    enable_tabline_ft_icon = true
    filetree_direction = "left"
    statusline_inactive_separator = "arrow"
    statusline_separator = "arrow"

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'ctrlp'

[[layers]]
name = 'incsearch'

[[layers]]
name = 'tools'

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
