#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
automatic_update = false
bootstrap_after = "init#after"
bootstrap_before = "init#before"
checkinstall = true
colorscheme = "spring-night"
colorscheme_bg = "dark"
disabled_plugins = []
enable_ale = true
enable_cursorcolumn = false
enable_cursorline = true
enable_guicolors = true
enable_language_specific_leader = false
enable_neomake = false
enable_os_fileformat_icon = true
enable_statusline_mode = true
enable_tabline_filetype_icon = true
filemanager = "vimfiler"
filetree_direction = "left"
github_username = "yukimemi"
relativenumber = false
simple_mode = true
statusline_separator = "arrow"
windows_index_type = 1

# Enable autocomplete layer
[[layers]]
name = "autocomplete"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = "shell"
default_position = "top"
default_height = 30

[[layers]]
name = "tools"
[[layers]]
name = "denite"
[[layers]]
name = "ctrlp"
[[layers]]
name = "VersionControl"
[[layers]]
name = "git"
[[layers]]
name = "lsp"
[[layers]]
name = "sudo"
[[layers]]
name = "tmux"
[[layers]]
name = "operator"
[[layers]]
name = "lang#toml"
[[layers]]
name = "lang#vim"
[[layers]]
name = "lang#rust"
[[layers]]
name = "lang#autohotkey"
[[layers]]
name = "lang#go"
[[layers]]
name = "lang#plantuml"
[[layers]]
name = "lang#ps1"
[[layers]]
name = "lang#python"
[[layers]]
name = "lang#javascript"
[[layers]]
name = "lang#json"

[[custom_plugins]]
name = "itchyny/vim-cursorword"
[[custom_plugins]]
name = "rhysd/vim-color-spring-night"
hook_add = '''
source $SPACE_VIM/rc/vim-airline.vim
'''

