#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    autocomplete_method = "coc"
    automatic_update = false
    bootstrap_after = "myspacevim#after"
    bootstrap_before = "myspacevim#before"
    buffer_index_type = 4
    colorscheme = "SpaceVim"
    colorscheme_bg = "dark"
    disabled_plugins = ["neco-syntax", "vim-surround", "clever-f.vim"]
    enable_ale = false
    enable_googlesuggest = true
    enable_guicolors = true
    enable_neomake = true
    enable_projects_cache = true
    enable_statusline_mode = false
    enable_tabline_filetype_icon = true
    filemanager = "vimfiler"
    filetree_direction = "left"
    lint_on_the_fly = true
    max_column = 120
    projects_cache_num = 50
    statusline_iseparator = "arrow"
    statusline_separator = "arrow"


[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'tools'

[[layers]]
name = 'checkers'

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = 'leaderf'

[[layers]]
name = 'japanese'

[[layers]]
name = 'operator'

[[layers]]
name = 'incsearch'

[[layers]]
name = 'test'

[[layers]]
name = 'ui'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#rust'

[[layers]]
name = 'lang#markdown'

[[custom_plugins]]
repo = 'kana/vim-operator-replace'
on_event = ['VimEnter']

[[custom_plugins]]
repo = 'machakann/vim-sandwich'
on_event = ['VimEnter']

[[custom_plugins]]
repo = 'gelguy/wilder.nvim'

[[custom_plugins]]
repo = 'lambdalisue/seethrough.vim'

[[custom_plugins]]
repo = 'thinca/vim-ambicmd'

[[custom_plugins]]
repo = 'rbtnn/vim-gloaded'

[[custom_plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = ['Gina']
hook_add = '''
source $SPACE_VIM/rc/gina.vim
'''

[[custom_plugins]]
repo = 'glidenote/memolist.vim'
on_cmd = ['MemoList', 'MemoNew', 'MemoGrep']
hook_add = '''
source $SPACE_VIM/rc/memolist.vim
'''

[[custom_plugins]]
repo = 'unblevable/quick-scope'
on_event = ['CursorHold', 'FocusLost']
hook_add = '''
source $SPACE_VIM/rc/quick-scope.vim
'''

[[custom_plugins]]
repo = 'haya14busa/vim-edgemotion'
on_map = '<Plug>'
hook_add = '''
source $SPACE_VIM/rc/vim-edgemotion.vim
'''

[[custom_plugins]]
repo = 'vim-scripts/autodate.vim'
on_event = ['InsertEnter']
hook_add = '''
source $SPACE_VIM/rc/autodate.vim
'''

[[custom_plugins]]
repo = 'thinca/vim-submode'
on_event = ['CursorHold', 'FocusLost']
hook_add = '''
source $SPACE_VIM/rc/vim-submode.vim
'''

[[custom_plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"

[[custom_plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"

