# =============================================================================
# File        : yazi.toml
# Author      : yukimemi
# Last Change : 2024/11/24 22:20:45.
# =============================================================================

# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
linemode = "mtime"

[opener]
edit = [
	{ run = '${EDITOR:-hitori} "$@"', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'hitori %*', orphan = true, desc = "hitori", for = "windows" },
]

[open]
prepend_rules = [{ name = "*/", use = ["reveal", "open", "edit"] }]
append_rules = [{ name = "*", use = ["open", "reveal", "edit"] }]

[plugin]
prepend_preloaders = [{ mime = "application/pdf", run = "noop" }]
prepend_previewers = [
	{ mime = "text/csv", run = "miller" },
	{ name = "*.md", run = "mdcat" },
	# Archive previewer
	{ mime = "application/*zip", run = "ouch" },
	{ mime = "application/x-tar", run = "ouch" },
	{ mime = "application/x-bzip2", run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar", run = "ouch" },
	{ mime = "application/x-xz", run = "ouch" },
	{ mime = "application/pdf", run = "noop" },
]
