# ======================================================================
# Unite {{{
# ======================================================================
[[plugins]]
repository = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'
  [plugins.commands]
  name = 'Unite'
  complete = 'customlist,unite#complete_source'

[[plugins]]
repository = 'Shougo/neomru.vim'
unite_sources = 'neomru'

[[plugins]]
repository = 'Shougo/unite-outline'
unite_sources = 'outline'

[[plugins]]
repository = 'thinca/vim-unite-history'
unite_sources = 'history'

[[plugins]]
repository = 'Shougo/unite-help'
unite_sources = 'help'

[[plugins]]
repository = 'tsukkee/unite-tag'
unite_sources = 'tag'

[[plugins]]
repository = 'Shougo/junkfile.vim'
unite_sources = 'junkfile'
commands = 'JunkfileOpen'

[[plugins]]
repository = 'thinca/vim-ref'
unite_sources = 'ref'
  [plugins.commands]
  name = 'Ref'
  complete = 'customlist,ref#complete'

[[plugins]]
repository = 'ujihisa/unite-colorscheme'
unite_sources = 'colorscheme'

[[plugins]]
repository = 'osyo-manga/unite-quickfix'
unite_sources = 'quickfix'

[[plugins]]
repository = 'osyo-manga/unite-filetype'
unite_sources = 'filetype'

[[plugins]]
repository = 'sorah/unite-ghq'
unite_sources = 'ghq'

[[plugins]]
repository = 'ujihisa/unite-colorscheme'
unite_sources = 'colorscheme'

[[plugins]]
repository = 'mattn/unite-vim_advent-calendar'
unite_sources = 'vim_advent_calendar'

[[plugins]]
repository = 'mattn/unite-advent_calendar'
unite_sources = 'advent_calendar'

[[plugins]]
repository = 'rhysd/unite-codic.vim'
depends = 'koron/codic-vim'
unite_sources = 'codic'
# }}}

# ======================================================================
# Complement {{{
# ======================================================================
[[plugins]]
repository = 'ujihisa/neco-look'
depends = 'Shougo/neocomplete.vim'
insert = 1

[[plugins]]
repository = 'Shougo/neco-vim'
depends = 'Shougo/neocomplete.vim'
filetypes = 'vim'

[[plugins]]
repository = 'mopp/googlesuggest-source.vim'
depends = 'Shougo/neocomplete.vim'
insert = 1
# }}}

# ======================================================================
# Search {{{
# ======================================================================
[[plugins]]
repository = 'osyo-manga/vim-over'
mappings = '<Plug>'
# }}}

# ======================================================================
# QuickRun {{{
# ======================================================================
[[plugins]]
repository = 'thinca/vim-quickrun'
mappings = '<Plug>(quickrun)'
commands = 'QuickRun'
on_source = 'osyo-manga/vim-watchdogs'

[[plugins]]
repository = 'osyo-manga/shabadou.vim'
depends = 'thinca/vim-quickrun'
on_source = 'thinca/vim-quickrun'
# }}}

# ======================================================================
# Comment {{{
# ======================================================================
[[plugins]]
repository = 'tyru/caw.vim'
filetypes = 'all'
# }}}

# ======================================================================
# Visual {{{
# ======================================================================
[[plugins]]
repository = 'kien/rainbow_parentheses.vim'
commands = 'RainbowParenthesesToggle'

[[plugins]]
repository = 'ntpeters/vim-better-whitespace'
filetypes = 'all'
# }}}

# ======================================================================
# Session {{{
# ======================================================================
[[plugins]]
repository = 'osyo-manga/vim-reanimate'
unite_sources = 'reanimate'
  [plugins.commands]
  name = ['ReanimateLoad']
  complete = 'customlist,s:save_point_completelist'
# }}}

# ======================================================================
# Operators {{{
# ======================================================================
[[plugins]]
repository = 'kana/vim-operator-user'
filetypes = 'all'

[[plugins]]
repository = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
mappings = '<Plug>(operator-replace)'

[[plugins]]
repository = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
mappings = '<Plug>(operator-surround'

[[plugins]]
repository = 'chikatoike/concealedyank.vim'
depends = 'vim-operator-user'
filetypes = 'vimshell'
mappings = '<Plug>(operator-concealedyank)'

[[plugins]]
repository = 'osyo-manga/vim-operator-blockwise'
depends = 'vim-operator-user'
mappings = '<Plug>(operator-blockwise'

[[plugins]]
repository = 'rhysd/vim-operator-trailingspace-killer'
depends = 'vim-operator-user'
mappings = '<Plug>(operator-trailingspace-killer)'

[[plugins]]
repository = 'rhysd/vim-clang-format'
depends = 'vim-operator-user'
mappings = '<Plug>(operator-clang-format)'

[[plugins]]
repository = 'osyo-manga/vim-operator-search'
depends = 'vim-operator-user'
mappings = '<Plug>(operator-search)'

[[plugins]]
repository = 'tyru/operator-star.vim'
depends = ['vim-operator-user', 'thinca/vim-visualstar']
mappings = ['<Plug>(operator-*)', '<Plug>(operator-g*)', '<Plug>(operator-#)', '<Plug>(operator-g#)']
# }}}

# ======================================================================
# Textobjs {{{
# ======================================================================
[[plugins]]
repository = 'kana/vim-textobj-user'
filetypes = 'all'

[[plugins]]
repository = 'osyo-manga/vim-textobj-multiblock'
depends = 'vim-textobj-user'
mappings = '<Plug>(textobj-multiblock'

[[plugins]]
repository = 'kana/vim-textobj-entire'
depends = 'vim-textobj-user'
mappings = '<Plug>(textobj-entire'

[[plugins]]
repository = 'kana/vim-textobj-fold'
depends = 'vim-textobj-user'
mappings = '<Plug>(textobj-fold'

[[plugins]]
repository = 'kana/vim-textobj-function'
depends = 'vim-textobj-user'
mappings = '<Plug>(textobj-function'

[[plugins]]
repository = 'kana/vim-textobj-indent'
depends = 'vim-textobj-user'
mappings = '<Plug>(textobj-indent'

[[plugins]]
repository = 'gilligan/textobj-lastpaste'
depends = 'vim-textobj-user'
mappings = '<Plug>(textobj-lastpaste-i)'
# }}}

# ======================================================================
# Git {{{
# ======================================================================
[[plugins]]
repository = 'gregsexton/gitv'
commands = 'Gitv'
# }}}

# ======================================================================
# Application {{{
# ======================================================================
[[plugins]]
repository = 'basyura/J6uil.vim'
function_prefix = 'J6uil'
unite_sources = 'J6uil'
depends = 'mattn/webapi-vim'
  [plugins.commands]
  name = 'J6uil'
  complete = 'custom,J6uil#complete#room'

[[plugins]]
repository =  'basyura/TweetVim''
depends = ['basyura/twibill.vim', 'tyru/open-browser.vim', 'basyura/bitly.vim', 'mattn/favstar-vim']
unite_sources = 'tweetvim'
commands = ['TweetVim', 'TweetVimUserStream','TweetVimSay']
filetypes = 'tweetvim'

[[plugins]]
repository = 'basyura/twibill.vim'

[[plugins]]
repository = 'tyru/open-browser.vim'

[[plugins]]
repository = 'basyura/bitly.vim'

[[plugins]]
repository = 'mattn/favstar-vim'

[[plugins]]
repository = 'supermomonga/jazzradio.vim'
unite_sources = 'jazzradio'
  [plugins.commands]
  name = 'JazzradioPlay'
  complete = 'customlist,Jazzradio#channel_key_complete'
# }}}

# ======================================================================
# Others {{{
# ======================================================================
[[plugins]]
repository = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
mappings = '<Plug>'
explorer = 1
  [plugins.commands]
  name = ['VimFiler']
  complete = 'customlist,vimfiler#complete'

[[plugins]]
repository = 'Shougo/vimshell.vim'
mappings = '<Plug>'
  [plugins.commands]
  name = 'VimShell'
  complete = 'customlist,vimshell#complete'

[[plugins]]
repository = 'supermomonga/vimshell-pure.vim'
depends = 'Shougo/vimshell.vim'
on_source = 'Shougo/vimshell.vim'

[[plugins]]
repository = 'yomi322/vim-gitcomplete'
filetypes = 'vimshell'

[[plugins]]
repository = 'Shougo/vinarise.vim'
  [plugins.commands]
  name = 'Vinarise'
  complete = 'file'

[[plugins]]
repository = 'vim-jp/vital.vim'
commands = 'Vitalize'

[[plugins]]
repository = 'ctrlpvim/ctrlp.vim'
commands = 'CtrlP'

[[plugins]]
repository = 'thinca/vim-fontzoom'
gui = 1
mappings = '<Plug>'

[[plugins]]
repository = 'thinca/vim-prettyprint'
commands = 'PP'

[[plugins]]
repository = 'thinca/vim-qfreplace'
filetypes = ['unite', 'quickfix']
commands = 'Qfreplace'

[[plugins]]
repository = 'itchyny/vim-external'
mappings = '<Plug>'

[[plugins]]
repository = 'tyru/restart.vim'
gui = 1
commands = 'Restart'

[[plugins]]
repository = 'tyru/winmove.vim'
depends = 'thinca/vim-submode'
mappings = '<Plug>'
gui = 1
augroup = 'winmove'

[[plugins]]
repository = 'matchit.zip'
mappings = [['nxo', '%', 'g%']]

[[plugins]]
repository = 't9md/vim-choosewin'
mappings = '<Plug>(choosewin)'
commands = ['FontReview', 'FontPerfSmall', 'ChooseWin', 'FontPerfLarge']

[[plugins]]
repository = 'lambdalisue/vim-fullscreen'
gui = 1
mappings = '<Plug>'

[[plugins]]
repository = 'syngan/vim-vimlint'
depends = 'ynkdir/vim-vimlparser'
function_prefix = 'vimlint'

[[plugins]]
repository = 'osyo-manga/vim-jplus'
mappings = '<Plug>'

[[plugins]]
repository = 'lambdalisue/vim-gista'
commands = 'Gista'
mappings = '<Plug>(gista-'
unite_sources = 'gista'

[[plugins]]
repository = 'kana/vim-niceblock'
mappings = '<Plug>'

[[plugins]]
repository = 'junegunn/vim-easy-align'
mappings = '<Plug>(EasyAlign)'

[[plugins]]
repository = 'tyru/capture.vim'
  [plugins.commands]
  name = 'Capture'
  complete = 'command'

[[plugins]]
repository = 'thinca/vim-prettyprint'
  [plugins.commands]
  name = 'PP'
  complete = 'expression'

[[plugins]]
repository = 'itchyny/thumbnail.vim'
  [plugins.commands]
  name = 'Thumbnail'
  complete = 'customlist,thumbnail#complete'

[[plugins]]
repository = 'mattn/vimplenote-vim'
commands = 'VimpleNote'

[[plugins]]
repository = 'koron/codic-vim'
  [plugins.commands]
  name = 'Codic'
  complete = 'customlist,codic#complete'

[[plugins]]
repository = 'soramugi/auto-ctags.vim'
commands = 'Ctags'

# [[plugins]]
# repository = 'yassu/todo-env.vim'
# filetypes = 'todo'

[[plugins]]
repository = 'fuenor/qfixhowm'
depends = 'fuenor/qfixgrep'
function_prefix = 'qfixmemo'
# }}}

