# ======================================================================
# Complement {{{
# ======================================================================
[[plugins]]
repository = 'Shougo/neocomplete.vim'
depends = 'Shougo/context_filetype.vim'
insert = 1

[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']
insert = 1
filetypes = 'snippet'
unite_sources = ['neosnippet', 'neosnippet/user', 'neosnippet/runtime']
# }}}

# ======================================================================
# Search {{{
# ======================================================================
[[plugins]]
repository = 'thinca/vim-visualstar'
mappings = '<Plug>(visualstar-'

[[plugins]]
repository = 't9md/vim-quickhl'
mappings = '<Plug>(quickhl-'
# }}}

# ======================================================================
# Git {{{
# ======================================================================
[[plugins]]
repository = 'tpope/vim-fugitive'
filetypes = 'all'
# }}}

# ======================================================================
# Filetype (haskell) {{{
# ======================================================================
[[plugins]]
repository = 'eagletmt/neco-ghc'
filetypes = 'haskell'

[[plugins]]
repository = 'kana/vim-filetype-haskell'
filetypes = 'haskell'

[[plugins]]
repository = 'eagletmt/ghcmod-vim'
filetypes = 'haskell'
# }}}

# ======================================================================
# Filetype (css) {{{
# ======================================================================
[[plugins]]
repository = 'hail2u/vim-css3-syntax'
filetypes = 'css'
# }}}

# ======================================================================
# Filetype (ruby) {{{
# ======================================================================
[[plugins]]
repository = 'vim-ruby/vim-ruby'
filetypes = 'ruby'

[[plugins]]
repository = 'todesking/ruby_hl_lvar.vim'
filetypes = 'ruby'

[[plugins]]
repository = 'osyo-manga/vim-monster'
filetypes = 'ruby'
# }}}

# ======================================================================
# Filetype (vim) {{{
# ======================================================================
[[plugins]]
repository = 'thinca/vim-themis'
filetypes = 'vim'
# }}}

# ======================================================================
# Filetype (vimperator) {{{
# ======================================================================
[[plugins]]
repository = 'superbrothers/vim-vimperator'
filetypes = 'vimperator'
# }}}

# ======================================================================
# Filetype (markdown) {{{
# ======================================================================
[[plugins]]
repository = 'rcmdnk/vim-markdown'
filetypes = ['markdown', 'mkd']

[[plugins]]
repository = 'mattn/vim-maketable'
commands = 'MakeTable'
# }}}

# ======================================================================
# Filetype (html) {{{
# ======================================================================
[[plugins]]
repository = 'mattn/emmet-vim'
filetypes = ['html', 'markdown', 'xml']
# }}}

# ======================================================================
# Filetype (javascript) {{{
# ======================================================================
# [[plugins]]
# repository = 'jiangmiao/simple-javascript-indenter'
# filetypes = 'javascript'

# [[plugins]]
# repository = 'jelera/vim-javascript-syntax'
# filetypes = 'javascript'

# [[plugins]]
# repository = 'jason0x43/vim-js-indent'
# filetypes = ['javascript', 'typescript']

[[plugins]]
repository = 'pangloss/vim-javascript'
filetypes = 'javascript'

[[plugins]]
repository = 'mxw/vim-jsx'
filetypes = ['javascript', 'jsx']

# [[plugins]]
# repository = 'mephux/vim-jsfmt'
# filetypes = ['javascript', 'jsx']
# }}}

# ======================================================================
# Filetype (coffee-script) {{{
# ======================================================================
[[plugins]]
repository = 'kchmck/vim-coffee-script'
filetypes = 'coffee'

# [[plugins]]
# repository = 'marijnh/tern_for_vim'
# filetypes = ['javascript', 'coffee']
# function_prefix = 'tern'
# }}}

# ======================================================================
# Filetype (typescript) {{{
# ======================================================================
[[plugins]]
repository = 'leafgarland/typescript-vim'
filetypes = 'typescript'

[[plugins]]
repository = 'Quramy/tsuquyomi'
filetypes = 'typescript'
# }}}

# ======================================================================
# Filetype (python) {{{
# ======================================================================
[[plugins]]
repository = 'hynek/vim-python-pep8-indent'
filetypes = 'python'

[[plugins]]
repository = 'davidhalter/jedi-vim'
filetypes = 'python'
# }}}

# ======================================================================
# Filetype (cpp) {{{
# ======================================================================
[[plugins]]
repository = 'vim-jp/cpp-vim'
filetypes = 'cpp'

[[plugins]]
repository =  'osyo-manga/vim-marching'
filetypes = 'cpp'

[[plugins]]
repository = 'rhysd/wandbox-vim'
filetypes = 'cpp'
# }}}

# ======================================================================
# Filetype (go) {{{
# ======================================================================
[[plugins]]
repository = 'fatih/vim-go'
filetypes = 'go'
# }}}

# ======================================================================
# Filetype (ps1) {{{
# ======================================================================
[[plugins]]
repository =   'PProvost/vim-ps1'
filetypes = 'ps1'
# }}}

# ======================================================================
# Filetype (rst) {{{
# ======================================================================
[[plugins]]
repository = 'Rykka/riv.vim'
filetypes = 'rst'
# }}}

# ======================================================================
# Filetype (clojure) {{{
# ======================================================================
[[plugins]]
repository =  'tpope/vim-fireplace'
depends = ['tpope/vim-classpath', 'guns/vim-clojure-static']
filetypes = 'clojure'

# [[plugins]]
# repository = 'thinca/vim-ft-clojure'
# filetypes = 'clojure'

[[plugins]]
repository = 'guns/vim-clojure-static'
filetypes = 'clojure'
# }}}

# ======================================================================
# Filetype (toml) {{{
# ======================================================================
[[plugins]]
repository = 'cespare/vim-toml'
filetypes = 'toml'
# }}}

# ======================================================================
# Filetype (plantuml) {{{
# ======================================================================
[[plugins]]
repository =  'aklt/plantuml-syntax'
filetypes = 'plantuml'
# }}}

# ======================================================================
# Filetype (diff) {{{
# ======================================================================
[[plugins]]
repository = 'thinca/vim-ft-diff_fold'
filetypes = 'diff'
# }}}

# ======================================================================
# Filetype (json) {{{
# ======================================================================
[[plugins]]
repository = 'elzr/vim-json'
filetypes = 'json'
# }}}

# ======================================================================
# Filetype (help) {{{
# ======================================================================
[[plugins]]
repository = 'vim-jp/vimdoc-ja'
filetypes = 'help'

[[plugins]]
repository = 'thinca/vim-ft-help_fold'
filetypes = 'help'
# }}}

# ======================================================================
# Others {{{
# ======================================================================
[[plugins]]
repository = 'rhysd/clever-f.vim'
mappings = '<Plug>(clever-f-'

[[plugins]]
repository = 'rhysd/accelerated-jk'
mappings = '<Plug>(accelerated_jk_'
# }}}

