# =============================================================================
# File        : base.yml
# Author      : yukimemi
# Last Change : 2024/05/28 16:45:04.
# =============================================================================

matches:
  - trigger: ";now"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  - trigger: ";date"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%Y/%m/%d"

  - trigger: ";tomorrow"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%x"
          offset: 86400

  - trigger: ";yesterday"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%x"
          offset: -86400
