[[ps1]]
name = "defaultcmd"
prefix = ""
suffix = ""
dst = "../cmd"
ext = ".cmd"
header = '''
@set __SCRIPTPATH=%~f0&@powershell -NoProfile -ExecutionPolicy ByPass -InputFormat None "$s=[scriptblock]::create((gc -enc utf8 -li \\"%~f0\\"|?{$_.readcount -gt 2})-join\\"`n\\");&$s" %*
@exit /b %errorlevel%
'''

[[ps1]]
name = "pausecmd"
prefix = ""
suffix = ""
dst = "../cmd"
ext = ".cmd"
header = '''
@set __SCRIPTPATH=%~f0&@powershell -NoProfile -ExecutionPolicy ByPass -InputFormat None "$s=[scriptblock]::create((gc -enc utf8 -li \\"%~f0\\"|?{$_.readcount -gt 2})-join\\"`n\\");&$s" %*&@pause
@exit /b %errorlevel%
'''

[[ps1]]
name = "waitcmd"
prefix = ""
suffix = ""
dst = "../cmd"
ext = ".cmd"
header = '''
@set __SCRIPTPATH=%~f0&@powershell -NoProfile -ExecutionPolicy ByPass -InputFormat None "$s=[scriptblock]::create((gc -enc utf8 -li \\"%~f0\\"|?{$_.readcount -gt 2})-join\\"`n\\");&$s" %*&@ping -n 30 localhost > nul
@exit /b %errorlevel%
'''

[[javascript]]
name = "default"
prefix = ""
suffix = ""
dst = "../cmd"
ext = ".cmd"
header = '''
@set @junk=1 /*
@cscript //nologo //e:jscript "%~f0" %*
@exit /b %errorlevel%
*/
'''

[[javascript]]
name = "pausecmd"
prefix = ""
suffix = ""
dst = "../cmd"
ext = ".cmd"
header = '''
@set @junk=1 /*
@cscript //nologo //e:jscript "%~f0" %*
@pause
@exit /b %errorlevel%
*/
'''

[[javascript]]
name = "waitcmd"
prefix = ""
suffix = ""
dst = "../cmd"
ext = ".cmd"
header = '''
@set @junk=1 /*
@cscript //nologo //e:jscript "%~f0" %*
@ping -n 30 localhost > nul
@exit /b %errorlevel%
*/
'''

[[dosbatch]]
name = "admincmd"
prefix = ""
suffix = "_a"
dst = "../cmd"
ext = ".bat"
header = '''
@openfiles > nul 2>&1
@if %errorlevel% equ 0 goto :ALREADY_ADMIN_PRIVILEGE
@powershell.exe -Command Start-Process \'%~f0\' %* -verb runas
@exit /b %errorlevel%
:ALREADY_ADMIN_PRIVILEGE
'''

