# =============================================================================
# File        : dein.toml
# Author      : yukimemi
# Last Change : 2020/08/23 16:54:33.
# =============================================================================

# ==================== Dein ====================== {{{1
[[plugins]]
repo = "Shougo/dein.vim" # {{{2


# ==================== Visual ==================== {{{1
[[plugins]]
repo = "NLKNguyen/papercolor-theme" # {{{2

[[plugins]]
repo = "lambdalisue/glyph-palette.vim" # {{{2
lazy = 1

[[plugins]]
repo = "lambdalisue/nerdfont.vim" # {{{2
lazy = 1

[[plugins]]
repo = "lambdalisue/readablefold.vim" # {{{2
on_event = ["CursorHold"]

[[plugins]]
repo = "itchyny/lightline.vim" # {{{2
if = "g:plugin_use_lightline"
hook_add = '''
source $VIM_PATH/rc/lightline.vim
'''
depends = ["vista.vim"]

[[plugins]]
repo = "vim-airline/vim-airline" # {{{2
if = "g:plugin_use_airline"
hook_add = '''
source $VIM_PATH/rc/vim-airline.vim
'''
[[plugins]]
repo = "vim-airline/vim-airline-themes" # {{{2
if = "g:plugin_use_airline"

[[plugins]]
repo = "nathanaelkane/vim-indent-guides" # {{{2
on_event = ["CursorHold"]
hook_add = '''
source $VIM_PATH/rc/vim-indent-guides.vim
'''

[[plugins]]
repo = "itchyny/vim-highlighturl" # {{{2
on_event = ["CursorHold"]

[[plugins]]
repo = "andymass/vim-matchup" # {{{2
on_event = ["CursorHold"]

[[plugins]]
repo = "ntpeters/vim-better-whitespace" # {{{2
on_event = ["CursorHold"]

[[plugins]]
repo = "jeffkreeftmeijer/vim-numbertoggle" # {{{2
on_event = ["CursorHold", "InsertEnter", "CursorMoved"]

[[plugins]]
repo = 'mattn/transparency-windows-vim' # {{{2
if = "g:is_windows && has('gui')"
hook_add = '''
source $VIM_PATH/rc/transparency-windows-vim.vim
'''

[[plugins]]
repo = 'mattn/vimtweak' # {{{2
if = "g:is_windows"

[[plugins]]
repo = 'lambdalisue/readablefold.vim' # {{{2
on_event  = ['CursorHold']

[[plugins]]
repo = 'lambdalisue/seethrough.vim' # {{{2
if = "!has('gui')"

[[plugins]]
repo = "gelguy/wilder.nvim" # {{{2
on_event  = ["CmdlineEnter", "CmdWinEnter"]
hook_add = '''
source $VIM_PATH/rc/wilder.nvim
'''

[[plugins]]
repo = 'LumaKernel/nvim-visual-eof.lua' # {{{2
if = "has('nvim')"
on_event  = ["VimEnter"]
hook_add = '''
source $VIM_PATH/rc/nvim-visual-eof.lua.vim
'''

# ==================== Complement ================ {{{1
[[plugins]]
repo = 'Shougo/context_filetype.vim' # {{{2
lazy = 1

[[plugins]]
repo = 'prabirshrestha/async.vim' # {{{2
if = 'g:plugin_use_asyncomplete'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim' # {{{2
if = 'g:plugin_use_asyncomplete'
hook_add = '''
source $VIM_PATH/rc/asyncomplete.vim
'''
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim' # {{{2
if = 'g:plugin_use_asyncomplete'
[[plugins]]
repo = 'prabirshrestha/vim-lsp' # {{{2
if = 'g:plugin_use_asyncomplete'
merged = 0
[[plugins]]
repo = 'mattn/vim-lsp-settings' # {{{2
if = 'g:plugin_use_asyncomplete'
merged = 0

[[plugins]]
repo = 'prabirshrestha/asyncomplete-buffer.vim' # {{{2
if = 'g:plugin_use_asyncomplete'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim' # {{{2
if = 'g:plugin_use_asyncomplete'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-emoji.vim' # {{{2
if = 'g:plugin_use_asyncomplete'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-tags.vim' # {{{2
if = "executable('ctags') && g:plugin_use_asyncomplete"

[[plugins]]
repo = 'hrsh7th/vim-vsnip' # {{{2
if = 'g:plugin_use_asyncomplete'
on_event = ['InsertEnter']
hook_source = '''
source $VIM_PATH/rc/vim-vsnip.vim
'''
[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
if = 'g:plugin_use_asyncomplete'
depends = ['vim-vsnip']

[[plugins]]
repo = "neoclide/coc.nvim" # {{{2
rev = "release"
if = "g:plugin_use_coc"
hook_add = '''
source $VIM_PATH/rc/coc.nvim
'''

# ==================== Utility =================== {{{1
[[plugins]]
repo = 'airblade/vim-rooter' # {{{2
on_event = ['CursorHold']
hook_add = '''
source $VIM_PATH/rc/vim-rooter.vim
'''

[[plugins]]
repo = 'thinca/vim-submode' # {{{2
on_event  = ['VimEnter']
hook_add = '''
source $VIM_PATH/rc/vim-submode.vim
'''

[[plugins]]
repo = 'junegunn/vim-easy-align' # {{{2
on_map = {v = '<Plug>(EasyAlign)'}
hook_add = '''
source $VIM_PATH/rc/vim-easy-align.vim
'''

[[plugins]]
repo = 'glidenote/memolist.vim' # {{{2
on_cmd = ['Memolist', 'MemoNew', 'MemoGrep']
hook_add = '''
source $VIM_PATH/rc/memolist.vim
'''

[[plugins]]
repo = 'vim-scripts/autodate.vim' # {{{2
on_event  = ['VimEnter']
hook_add = '''
source $VIM_PATH/rc/autodate.vim
'''

[[plugins]]
repo = 'mbbill/undotree' # {{{2
on_cmd = ['UndotreeToggle']
hook_add = '''
source $VIM_PATH/rc/undotree.vim
'''

[[plugins]]
repo = 'tpope/vim-repeat' # {{{2

[[plugins]]
repo = 'tyru/capture.vim' # {{{2
on_cmd = ['Capture']

[[plugins]]
repo = 'Shougo/echodoc.vim' # {{{2
depends = ['context_filetype.vim']
on_event = ["InsertEnter"]
hook_add = '''
source $VIM_PATH/rc/echodoc.vim
'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim' # {{{2
if = "g:plugin_use_ctrlp"
on_cmd = ['CtrlP', 'CtrlPBuffer', 'CtrlPCurFile', 'CtrlPMRUFiles']
hook_add = '''
source $VIM_PATH/rc/ctrlp.vim
'''
[[plugins]]
repo = 'kaneshin/ctrlp-filetype' # {{{2
if = "g:plugin_use_ctrlp"
depends = ['ctrlp.vim']
on_cmd = ['CtrlPFiletype']
[[plugins]]
repo = 'kaneshin/ctrlp-memolist' # {{{2
if = "g:plugin_use_ctrlp"
depends = ['ctrlp.vim']
on_cmd = ['CtrlPMemolist']
[[plugins]]
repo = 'mattn/ctrlp-launcher' # {{{2
if = "g:plugin_use_ctrlp"
depends = ['ctrlp.vim']
on_cmd = ['CtrlPLauncher']
[[plugins]]
repo = 'mattn/ctrlp-mark' # {{{2
if = "g:plugin_use_ctrlp"
depends = ['ctrlp.vim']
on_cmd = ['CtrlPMark']
[[plugins]]
repo = 'mattn/ctrlp-vimhelpjp' # {{{2
if = "g:plugin_use_ctrlp"
depends = ['ctrlp.vim', 'webapi-vim']
on_cmd = 'VimHelpJp'
[[plugins]]
repo = 'suy/vim-ctrlp-commandline' # {{{2
if = "g:plugin_use_ctrlp"
depends = ['ctrlp.vim']
on_cmd = ['CtrlPCommandLine']
[[plugins]]
repo = 'ompugao/ctrlp-history' # {{{2
if = "g:plugin_use_ctrlp"
depends = ['ctrlp.vim']
on_cmd = ['CtrlPCmdHistory', 'CtrlPSearchHistory']

[[plugins]]
repo = 'liuchengxu/vim-clap' # {{{2
if = "g:plugin_use_clap"
on_cmd = ['Clap']
hook_add = '''
source $VIM_PATH/rc/vim-clap.vim
'''
hook_post_update = '''
call clap#helper#build_all()
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode' # {{{2
on_ft = ['markdown']

[[plugins]]
repo = 'qpkorr/vim-renamer' # {{{2
on_cmd = ['Renamer']
hook_add = '''
source $VIM_PATH/rc/vim-renamer.vim
'''

[[plugins]]
repo = 'itchyny/vim-external' # {{{2
on_map = '<Plug>'
hook_add = '''
source $VIM_PATH/rc/vim-external.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim' # {{{2
if = "g:plugin_use_defx"
depends = ['defx-icons']
on_cmd = ['Defx']
hook_add = '''
source $VIM_PATH/rc/defx.nvim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'
lazy = 1

[[plugins]]
repo = 'lambdalisue/vim-findent' # {{{2
on_cmd = ['Findent']

[[plugins]]
repo = 'tmux-plugins/vim-tmux-focus-events' # {{{2
if  = '!g:is_windows'

[[plugins]]
repo = 'roxma/vim-tmux-clipboard' # {{{2
if  = '!g:is_windows'

[[plugins]]
repo = 'roxma/nvim-yarp' # {{{2
if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc' # {{{2
if = '!has("nvim")'

[[plugins]]
repo = 'mattn/webapi-vim' # {{{2
lazy = 1

[[plugins]]
repo = 'lambdalisue/fern.vim' # {{{2
depends = ['fern-bookmark.vim', 'fern-comparator-lexical.vim', 'fern-git.vim', 'fern-renderer-nerdfont.vim', 'fern-git-status.vim', 'fern-mapping-git.vim']
on_cmd = 'Fern'
hook_add = '''
source $VIM_PATH/rc/fern.vim
'''
if = "g:plugin_use_fern"
[[plugins]]
repo = 'lambdalisue/fern-bookmark.vim'
lazy = 1
[[plugins]]
repo = 'lambdalisue/fern-comparator-lexical.vim'
lazy = 1
[[plugins]]
repo = 'lambdalisue/fern-git.vim'
lazy = 1
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
lazy = 1
depends = ['nerdfont.vim', 'glyph-palette.vim']
[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
lazy = 1
[[plugins]]
repo = 'lambdalisue/fern-mapping-git.vim'
lazy = 1

[[plugins]]
repo = 'editorconfig/editorconfig-vim' # {{{2
on_event = ['VimEnter']

[[plugins]]
repo = 'haya14busa/vim-edgemotion' # {{{2
on_map = '<Plug>'
hook_add = '''
source $VIM_PATH/rc/vim-edgemotion.vim
'''

[[plugins]]
repo = 'thinca/vim-quickrun' # {{{2
on_map = '<Plug>'
hook_add = '''
source $VIM_PATH/rc/vim-quickrun.vim
'''

[[plugins]]
repo = 'lambdalisue/vim-quickrun-neovim-job' # {{{2
on_source = 'vim-quickrun'

[[plugins]]
repo = 'twitvim/twitvim' # {{{2
on_cmd = ['FriendsTwitter', 'UserTwitter', 'RepliesTwitter', 'DMTwitter']
hook_add = '''
source $VIM_PATH/rc/twitvim.vim
'''

[[plugins]]
repo = 'tyru/open-browser.vim' # {{{2
on_source = ['twitvim']
on_ft = ['markdown']

[[plugins]]
repo = 'rickhowe/diffchar.vim' # {{{2
on_if = '&diff'

[[plugins]]
repo = 'liuchengxu/vim-which-key' # {{{2
on_event  = ['CursorHold']

[[plugins]]
repo = 'liuchengxu/vista.vim' # {{{2
lazy = 1

[[plugins]]
repo = 'thinca/vim-ambicmd'
hook_add = '''
source $VIM_PATH/rc/vim-ambicmd.vim
'''

# ==================== Denite ==================== {{{1
[[plugins]]
repo = 'Shougo/denite.nvim' # {{{2
if = "has('python3') && g:plugin_use_denite"
depends = ['neomru.vim']
on_cmd = ['Denite']
hook_add = '''
source $VIM_PATH/rc/denite.nvim
'''

[[plugins]]
repo = 'Shougo/neomru.vim' # {{{2
lazy = 1

[[plugins]]
repo = 'Shougo/junkfile.vim' # {{{2
on_source = 'denite.nvim'
on_cmd = 'JunkfileOpen'

# ==================== Search ==================== {{{1
[[plugins]]
repo = 'haya14busa/vim-asterisk' # {{{2
on_map = '<Plug>'
hook_add = '''
source $VIM_PATH/rc/vim-asterisk.vim
'''

[[plugins]]
repo = 't9md/vim-quickhl' # {{{2
on_event  = ['CursorHold']
hook_add = '''
source $VIM_PATH/rc/vim-quickhl.vim
'''

[[plugins]]
repo = 'itchyny/vim-parenmatch' # {{{2
on_event  = ['CursorHold']
hook_add = '''
source $VIM_PATH/rc/vim-parenmatch.vim
'''

[[plugins]]
repo = 'itchyny/vim-cursorword' # {{{2
on_event  = ['CursorHold']
hook_add = '''
source $VIM_PATH/rc/vim-cursorword.vim
'''

[[plugins]]
repo = 'thinca/vim-qfreplace' # {{{2
on_ft = ['quickfix']

[[plugins]]
repo = 'mhinz/vim-grepper' # {{{2
on_cmd = 'Grepper'
on_map = '<Plug>'
hook_source = '''
source $VIM_PATH/rc/vim-grepper.vim
'''
[[plugins]]
repo = 'eugen0329/vim-esearch'
on_map = '<Plug>'
hook_add = '''
source $VIM_PATH/rc/vim-esearch.vim
'''

# ==================== Operators ================= {{{1
[[plugins]]
repo = 'kana/vim-operator-user' # {{{2

[[plugins]]
repo = 'kana/vim-operator-replace' # {{{2
depends = 'vim-operator-user'
on_map = '<Plug>'
hook_add = '''
source $VIM_PATH/rc/vim-operator-replace.vim
'''

[[plugins]]
repo = 'rhysd/vim-operator-surround' # {{{2
depends = 'vim-operator-user'
on_map = '<Plug>'
hook_add = '''
source $VIM_PATH/rc/vim-operator-surround.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-operator-search' # {{{2
depends = 'vim-operator-user'
on_map = '<Plug>'
hook_add = '''
source $VIM_PATH/rc/vim-operator-search.vim
'''

[[plugins]]
repo = 'haya14busa/vim-operator-flashy' # {{{2
depends = 'vim-operator-user'
on_map = '<Plug>'
hook_add = '''
source $VIM_PATH/rc/vim-operator-flashy.vim
'''

# ==================== Textobjs ================== {{{1
[[plugins]]
repo = 'kana/vim-textobj-user' # {{{2

[[plugins]]
repo = 'kana/vim-textobj-entire' # {{{2
depends = 'vim-textobj-user'
on_map = {nox = '<Plug>'}
hook_add = '''
source $VIM_PATH/rc/vim-textobj-entire.vim
'''

[[plugins]]
repo = 'kana/vim-textobj-fold' # {{{2
depends = 'vim-textobj-user'
on_map = {nox = '<Plug>'}
hook_add = '''
source $VIM_PATH/rc/vim-textobj-fold.vim
'''

[[plugins]]
repo = 'kana/vim-textobj-function' # {{{2
depends = 'vim-textobj-user'
on_map = {nox = '<Plug>'}
hook_add = '''
source $VIM_PATH/rc/vim-textobj-function.vim
'''

[[plugins]]
repo = 'kana/vim-textobj-indent' # {{{2
depends = 'vim-textobj-user'
on_map = {nox = '<Plug>'}
hook_add = '''
source $VIM_PATH/rc/vim-textobj-indent.vim
'''

[[plugins]]
repo = 'gilligan/textobj-lastpaste' # {{{2
depends = 'vim-textobj-user'
on_map = {nox = '<Plug>'}
hook_add = '''
source $VIM_PATH/rc/textobj-lastpaste.vim
'''

[[plugins]]
repo = 'kana/vim-textobj-line' # {{{2
depends = 'vim-textobj-user'
on_map = {nox = '<Plug>'}
hook_add = '''
source $VIM_PATH/rc/vim-textobj-line.vim
'''

# ==================== Comment =================== {{{1
[[plugins]]
repo = 'tyru/caw.vim' # {{{2
on_map = '<Plug>'
hook_add = '''
source $VIM_PATH/rc/caw.vim
'''

# ==================== Yank/Paste ================ {{{1
[[plugins]]
repo = 'LeafCage/yankround.vim' # {{{2
hook_add = '''
source $VIM_PATH/rc/yankround.vim
'''

# ==================== Git ======================= {{{1
[[plugins]]
repo = 'lambdalisue/gina.vim' # {{{2
hook_add = '''
source $VIM_PATH/rc/gina.vim
'''

# ==================== Filetype (all) ============= {{{1
[[plugins]]
repo = 'sheerun/vim-polyglot' # {{{2
merged = 0
hook_add = '''
source $VIM_PATH/rc/vim-polyglot.vim
'''

# ==================== Filetype (plantuml) ======= {{{1
[[plugins]]
repo = 'scrooloose/vim-slumlord' # {{{2
on_ft = 'plantuml'
hook_add = '''
source $VIM_PATH/rc/vim-slumlord.vim
'''

# ==================== Filetype (markdown) ======= {{{1
[[plugins]]
repo = 'iamcco/markdown-preview.nvim' # {{{2
on_ft = 'markdown'
on_cmd = ['MarkdownPreview']
hook_post_update = '''
call dein#source('markdown-preview.nvim')
call mkdp#util#install()
'''

# ==================== Filetype (Haskell) ======== {{{1
[[plugins]]
repo = 'eagletmt/ghcmod-vim' # {{{2
if = "executable('stack')"
on_ft = 'haskell'
build = 'stack install ghc-mod'
hook_add = '''
source $VIM_PATH/rc/ghcmod-vim.vim
'''

[[plugins]]
repo = 'itchyny/vim-haskell-indent' # {{{2
on_ft = 'haskell'

[[plugins]]
repo = 'itchyny/vim-haskell-sort-import' # {{{2
on_ft = 'haskell'
hook_add = '''
source $VIM_PATH/rc/vim-haskell-sort-import.vim
'''


# ==================== Filetype (SQL) ============ {{{1
[[plugins]]
repo = 'b4b4r07/vim-sqlfmt' # {{{2
on_ft = 'sql'
build = 'go get github.com/jackc/sqlfmt'
hook_add = '''
source $VIM_PATH/rc/vim-sqlfmt.vim
'''

# ==================== Filetype (purescript) ===== {{{1
[[plugins]]
repo = 'FrigoEU/psc-ide-vim' # {{{2
on_ft = 'purescript'


# ==================== Filetype (csv) ============ {{{1
[[plugins]]
repo = 'mechatroner/rainbow_csv' # {{{2
on_ft = 'csv'

# ==================== After ftplugin ============ {{{1
[ftplugin]
_ = '''
set formatoptions-=ro
'''

dosbatch = '''
setl fenc=cp932 ff=dos
'''

html = '''
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_syntax_folding = 1
setl noexpandtab
setl ts=4 sw=4 sts=0
setl foldmethod=syntax
'''

csv = '''
setl nowrap
'''

log = '''
setl nowrap
'''

mail = '''
setl ff=dos
setl fenc=cp932
'''

markdown = '''
setl formatoptions+=t
setl conceallevel=0
'''

go = '''
setl completeopt+=preview
'''

ps1 = '''
setl ts=2 sw=2 sts=0
setl expandtab
setl foldmethod=syntax
'''

python = '''
setl cinwords=if,elif,else,for,while,try,except,finally,def,class
setl expandtab
setl ts=8 sw=4 sts=4
setl foldmethod=indent foldlevel=99
'''

xml = '''
setl noexpandtab
setl ts=4 sw=4 sts=0

let g:xml_syntax_folding = 1
setl foldmethod=syntax
'''

elm = '''
setl ts=4 sw=4 sts=0
'''

javascript = '''
'''

css = '''
'''

rust = '''
'''

text = '''
setl noexpandtab
setl ts=4 sw=4 sts=0
'''

# vim:fdm=marker fdc=3:
