# Paneru configuration

[options]
animation_speed = 20

[padding]
top = 5
bottom = 5
left = 0
right = 0

[decorations.active.border]
enabled = true
color = "#89b4fa"
width = 2.0
radius = 12.0

[windows.all]
title = ".*"
horizontal_padding = 5
vertical_padding = 0

[windows.shun]
title = ".*"
bundle_id = "com.yukimemi.shun"
floating = true

[bindings]
window_focus_west = "ctrl + cmd - h"
window_focus_east = "ctrl + cmd - l"

window_swap_west = "ctrl + cmd + shift - h"
window_swap_east = "ctrl + cmd + shift - l"

