name: ci

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run CI
        run: deno task ci
