name: Deno CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deno-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run Deno CI task
        run: deno task ci
